name: Build

on:
  push:
    branches: [ main, release ]
  pull_request:

jobs:
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - name: Docker Login
        uses: docker/login-action@v2.0.0
        with:
          registry: testperfect.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build Docker image
        run: docker build . -f frontend.Dockerfile --tag testperfect.azurecr.io/testperfect/tra-ui:${SHORT_SHA} --build-arg=GIT_BRANCH=$(git rev-parse --abbrev-ref HEAD) --build-arg=GIT_COMMIT=${SHORT_SHA}
      - name: Push Docker image
        run: docker push testperfect.azurecr.io/testperfect/tra-ui:${SHORT_SHA}